item { 
	name:'car'
	id:1
}
item { 
	name:'person'
	id:2
}
item { 
	name:'bike'
	id:3
}
item { 
	name:'bus'
	id:4
}
item { 
	name:'truck'
	id:5
}
item { 
	name:'dog'
	id:6
}
item { 
	name:'cat'
	id:7
}
